CREATE TABLE IF NOT EXISTS navigation_controls (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nav_key VARCHAR(120) NOT NULL,
    location VARCHAR(40) NOT NULL,
    section_key VARCHAR(60) NOT NULL DEFAULT 'default',
    label VARCHAR(120) NOT NULL,
    custom_url VARCHAR(500) NOT NULL DEFAULT '',
    icon_class VARCHAR(120) NOT NULL DEFAULT '',
    badge_text VARCHAR(40) NOT NULL DEFAULT '',
    sort_order INT NOT NULL DEFAULT 0,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    audience VARCHAR(20) NOT NULL DEFAULT 'all',
    item_type VARCHAR(20) NOT NULL DEFAULT 'link',
    children_section_key VARCHAR(60) NOT NULL DEFAULT '',
    admin_hint VARCHAR(255) NOT NULL DEFAULT '',
    admin_route_hint VARCHAR(500) NOT NULL DEFAULT '',
    is_system TINYINT(1) NOT NULL DEFAULT 0,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_navigation_controls_key (nav_key),
    KEY idx_navigation_controls_location (location),
    KEY idx_navigation_controls_section (section_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
