<?php
function engagementGetAnnouncementForLogin(int $uid,PDO $db=null):?array{$db=$db?:getDBConnection();if($uid<1||!engagementSchemaAvailable($db)||!empty($_SESSION['engagement_announcement_closed']))return null;$id=(int)($_SESSION['engagement_announcement_id']??0);$sql="SELECT n.* FROM engagement_announcements n JOIN users u ON u.id=? LEFT JOIN engagement_announcement_events e ON e.announcement_id=n.id AND e.user_id=u.id WHERE n.is_active=1 AND(n.starts_at IS NULL OR n.starts_at<=NOW())AND(n.ends_at IS NULL OR n.ends_at>=NOW())AND(n.audience='all' OR(n.audience='registered_after' AND u.created_at>=n.audience_after))AND e.dismissed_forever_at IS NULL";$p=[$uid];if($id){$sql.=' AND n.id=? LIMIT 1';$p[]=$id;}else{$sql.=' ORDER BY RAND() LIMIT 1';}$q=$db->prepare($sql);$q->execute($p);$r=$q->fetch();if(!$r)return null;$_SESSION['engagement_announcement_id']=(int)$r['id'];if(empty($_SESSION['engagement_announcement_view_recorded'])){$db->prepare("INSERT INTO engagement_announcement_events(announcement_id,user_id,view_count,first_viewed_at,last_viewed_at)VALUES(?,?,1,NOW(),NOW()) ON DUPLICATE KEY UPDATE view_count=view_count+1,last_viewed_at=NOW()")->execute([(int)$r['id'],$uid]);$_SESSION['engagement_announcement_view_recorded']=1;}return$r;}
function engagementDismissAnnouncement(int $uid,int $id,bool $forever,PDO $db=null):void{if($uid<1||$id<1)throw new InvalidArgumentException('Invalid announcement.');$_SESSION['engagement_announcement_closed']=1;if($forever){$db=$db?:getDBConnection();$db->prepare("INSERT INTO engagement_announcement_events(announcement_id,user_id,dismissed_forever_at)VALUES(?,?,NOW()) ON DUPLICATE KEY UPDATE dismissed_forever_at=NOW()")->execute([$id,$uid]);}}
function engagementDashboardState(int $uid,PDO $db=null):array{return['announcement'=>engagementGetAnnouncementForLogin($uid,$db),'assignment'=>engagementGetUserAssignment($uid,$db)];}
function enforceSocialEngagementRequestGate():void{if(PHP_SAPI==='cli'||defined('COINREX_SKIP_ENGAGEMENT_GATE'))return;$path=str_replace('\\','/',(string)($_SERVER['SCRIPT_NAME']??''));foreach(['/admin/','/auth/','/public/dashboard.php','/api/social-engagement/']as$a)if(strpos($path,$a)!==false)return;if(empty($_SESSION['user_id'])||!engagementSchemaAvailable()||!engagementUserIsBlocked((int)$_SESSION['user_id']))return;if(strpos($path,'/api/')!==false){http_response_code(423);header('Content-Type: application/json');echo json_encode(['success'=>false,'code'=>'social_gate_required','message'=>'Complete social onboarding from dashboard.']);exit;}header('Location: '.BASE_URL.'/public/dashboard.php?social_gate=required');exit;}
function engagementSchemaAvailable(PDO $db=null,bool $refresh=false):bool {
 static $results=[];$db=$db?:getDBConnection();$key=spl_object_id($db);if(!$refresh&&array_key_exists($key,$results))return $results[$key];try{$q=$db->prepare("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=? AND TABLE_NAME IN ('social_gate_campaigns','social_gate_assignments','social_gate_evidence','engagement_announcements','engagement_announcement_events')");$q->execute([DB_NAME]);return $results[$key]=((int)$q->fetchColumn()===5);}catch(Throwable $e){return $results[$key]=false;}
}
function ensureEngagementSchema(PDO $db=null):bool {
 $db=$db?:getDBConnection();if(engagementSchemaAvailable($db))return true;$path=dirname(__DIR__,2).'/database/migrations/2026_08_27_social_engagement.sql';if(!is_file($path))return false;try{$sql=(string)file_get_contents($path);$sql=preg_replace('/^\s*USE\s+[^;]+;\s*/i','',$sql,1);foreach(preg_split('/;\s*(?:\r?\n|$)/',$sql)as$statement){$statement=trim($statement);if($statement!=='')$db->exec($statement);}}catch(Throwable $e){error_log('Engagement schema setup failed: '.$e->getMessage());}return engagementSchemaAvailable($db,true);
}
function engagementGetActiveCampaign(PDO $db=null):?array{$db=$db?:getDBConnection();if(!engagementSchemaAvailable($db))return null;$r=$db->query("SELECT * FROM social_gate_campaigns WHERE is_active=1 ORDER BY activated_at DESC,id DESC LIMIT 1")->fetch();return is_array($r)?$r:null;}
function engagementEnrollUser(int $uid,PDO $db=null):?int{$db=$db?:getDBConnection();$c=engagementGetActiveCampaign($db);if($uid<1||!$c)return null;$db->prepare("INSERT IGNORE INTO social_gate_assignments(campaign_id,user_id,status)VALUES(?,?,'required')")->execute([(int)$c['id'],$uid]);$q=$db->prepare('SELECT id FROM social_gate_assignments WHERE campaign_id=? AND user_id=?');$q->execute([(int)$c['id'],$uid]);return (int)($q->fetchColumn()?:0)?:null;}
function engagementGetUserAssignment(int $uid,PDO $db=null):?array{$db=$db?:getDBConnection();if($uid<1||!engagementSchemaAvailable($db))return null;$q=$db->prepare("SELECT a.*,c.name campaign_name,c.platform,c.modal_title,c.modal_message,c.cta_label,c.cta_url,c.max_strikes,c.is_active campaign_active FROM social_gate_assignments a JOIN social_gate_campaigns c ON c.id=a.campaign_id WHERE a.user_id=? ORDER BY a.id DESC LIMIT 1");$q->execute([$uid]);$r=$q->fetch();if(!$r)return null;if(in_array($r['status'],['required','pending'],true)&&(int)$r['strike_count']>=max(1,(int)$r['max_strikes'])){$db->prepare("UPDATE social_gate_assignments SET status='waived',waived_at=NOW(),admin_note='Automatically waived at strike limit' WHERE id=?")->execute([(int)$r['id']]);$r['status']='waived';}$r['is_blocked']=(int)$r['campaign_active']===1&&$r['status']==='required';return$r;}
function engagementUserIsBlocked(int $uid,PDO $db=null):bool{$a=engagementGetUserAssignment($uid,$db);return(bool)($a&&!empty($a['is_blocked']));}
function engagementTrackCtaClick(int $uid,int $aid,PDO $db=null):array{$db=$db?:getDBConnection();$q=$db->prepare("SELECT a.status,c.cta_url,c.is_active FROM social_gate_assignments a JOIN social_gate_campaigns c ON c.id=a.campaign_id WHERE a.id=? AND a.user_id=?");$q->execute([$aid,$uid]);$r=$q->fetch();if(!$r||!$r['is_active']||$r['status']!=='required')throw new RuntimeException('Campaign unavailable.');$url=trim($r['cta_url']);if(!filter_var($url,FILTER_VALIDATE_URL))throw new RuntimeException('Invalid destination.');$db->prepare('UPDATE social_gate_assignments SET cta_clicked_at=NOW() WHERE id=?')->execute([$aid]);return['url'=>$url];}
function engagementNormalizeUrl(string $url): string {
 $url=html_entity_decode($url,ENT_QUOTES|ENT_HTML5,'UTF-8');
 $url=preg_replace('/[\x{200B}\x{200C}\x{200D}\x{2060}\x{FEFF}]/u','',$url)??$url;
 $url=trim($url," \t\n\r\0\x0B\"'");
 if(preg_match('/^\[[^\]]*\]\((https?:\/\/[^)]+)\)$/iu',$url,$match))$url=$match[1];
 return str_replace(['\\:','\\/','\\_'],[':','/','_'],$url);
}
function engagementValidHttpsUrl(string $url): bool {
 if(!filter_var($url,FILTER_VALIDATE_URL))return false;
 $parts=parse_url($url);
 return is_array($parts)&&strtolower((string)($parts['scheme']??''))==='https'&&!empty($parts['host']);
}
function engagementValidProfileUrl(string $p,string $url):bool{$url=engagementNormalizeUrl($url);if(!engagementValidHttpsUrl($url))return false;$h=preg_replace('/^www\\./','',strtolower((string)parse_url($url,PHP_URL_HOST)));return$p==='x'?in_array($h,['x.com','twitter.com'],true):($p==='telegram'&&in_array($h,['t.me','telegram.me'],true));}
function engagementSubmitEvidence(int $uid,int $aid,string $handle,string $profile,array $file,PDO $db=null):array{$db=$db?:getDBConnection();$handle=ltrim(trim($handle),'@');$profile=engagementNormalizeUrl($profile);$saved=null;if(!preg_match('/^[A-Za-z0-9_.-]{3,120}$/',$handle))throw new InvalidArgumentException('Enter a valid social handle.');$db->beginTransaction();try{$q=$db->prepare("SELECT a.*,c.platform,c.is_active FROM social_gate_assignments a JOIN social_gate_campaigns c ON c.id=a.campaign_id WHERE a.id=? AND a.user_id=? FOR UPDATE");$q->execute([$aid,$uid]);$a=$q->fetch();if(!$a||!$a['is_active']||$a['status']!=='required')throw new RuntimeException('Evidence request inactive.');if(empty($a['cta_clicked_at']))throw new RuntimeException('Open the social channel first.');if(!engagementValidProfileUrl($a['platform'],$profile))throw new InvalidArgumentException('Profile URL does not match platform.');if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||empty($file['tmp_name']))throw new InvalidArgumentException('Screenshot required.');if(($file['size']??0)<1||$file['size']>5242880)throw new InvalidArgumentException('Screenshot must be 5 MB or smaller.');$mime=(string)(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($ext[$mime]))throw new InvalidArgumentException('Use JPG, PNG, or WebP.');$dir=dirname(__DIR__,2).'/uploads/social-gate/';if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))throw new RuntimeException('Storage unavailable.');$name='social_'.$uid.'_'.bin2hex(random_bytes(16)).'.'.$ext[$mime];$saved=$dir.$name;if(!move_uploaded_file($file['tmp_name'],$saved))throw new RuntimeException('Could not save screenshot.');$url=rtrim(BASE_URL,'/').'/uploads/social-gate/'.$name;$nq=$db->prepare('SELECT COALESCE(MAX(attempt_number),0)+1 FROM social_gate_evidence WHERE assignment_id=?');$nq->execute([$aid]);$num=(int)$nq->fetchColumn();$q=$db->prepare("INSERT INTO social_gate_evidence(assignment_id,attempt_number,handle,profile_url,screenshot_url,status,submitted_ip,submitted_user_agent)VALUES(?,?,?,?,?,'pending',?,?)");$q->execute([$aid,$num,$handle,$profile,$url,substr(getClientIpAddress(),0,45),substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,500)]);$id=(int)$db->lastInsertId();$db->prepare("UPDATE social_gate_assignments SET status='pending',admin_note=NULL WHERE id=?")->execute([$aid]);$db->commit();return['evidence_id'=>$id,'message'=>'Evidence submitted. Access enabled while under review.'];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();if($saved&&is_file($saved))@unlink($saved);throw$e;}}
