<?php
/**
 * Wallet Platform Navigation
 * Independent navigation for wallet.coinrex.xyz platform
 * Does not modify main coinrex.xyz navigation
 */

// Wallet platform navigation items - these are ONLY used by wallet.php
// Main coinrex.xyz navigation remains completely untouched

$wallet_navigation_items = [
    'wallet_home' => [
        'nav_key' => 'wallet_home',
        'location' => 'header',
        'section_key' => 'primary',
        'label' => 'Home',
        'route_key' => 'home',
        'icon_class' => 'fas fa-home',
        'badge_text' => '',
        'sort_order' => 10,
        'is_enabled' => 1,
        'audience' => 'all',
        'item_type' => 'link',
        'admin_hint' => 'Home link pointing to main coinrex.xyz website',
        'admin_route_hint' => 'coinrex.xyz',
        'active_pages' => ['wallet', 'index', 'home'],
    ],
    'wallet_about' => [
        'nav_key' => 'wallet_about',
        'location' => 'header',
        'section_key' => 'primary',
        'label' => 'About',
        'route_key' => 'about',
        'icon_class' => 'fas fa-info-circle',
        'badge_text' => '',
        'sort_order' => 20,
        'is_enabled' => 1,
        'audience' => 'all',
        'item_type' => 'link',
        'admin_hint' => 'About page for wallet platform',
        'admin_route_hint' => BASE_URL . '/wallet_about.php',
        'active_pages' => ['wallet_about'],
    ],
    'wallet_contact' => [
        'nav_key' => 'wallet_contact',
        'location' => 'header',
        'section_key' => 'primary',
        'label' => 'Contact',
        'route_key' => 'contact',
        'icon_class' => 'fas fa-envelope',
        'badge_text' => '',
        'sort_order' => 30,
        'is_enabled' => 1,
        'audience' => 'all',
        'item_type' => 'link',
        'admin_hint' => 'Contact page for wallet platform',
        'admin_route_hint' => BASE_URL . '/wallet_contact.php',
        'active_pages' => ['wallet_contact'],
    ],
    'wallet_privacy' => [
        'nav_key' => 'wallet_privacy',
        'location' => 'header',
        'section_key' => 'primary',
        'label' => 'Privacy',
        'route_key' => 'privacy',
        'icon_class' => 'fas fa-shield-alt',
        'badge_text' => '',
        'sort_order' => 40,
        'is_enabled' => 1,
        'audience' => 'all',
        'item_type' => 'link',
        'admin_hint' => 'Privacy policy page for wallet platform',
        'admin_route_hint' => BASE_URL . '/wallet_privacy.php',
        'active_pages' => ['wallet_privacy'],
    ],
    'wallet_terms' => [
        'nav_key' => 'wallet_terms',
        'location' => 'header',
        'section_key' => 'primary',
        'label' => 'Terms',
        'route_key' => 'terms',
        'icon_class' => 'fas fa-file-contract',
        'badge_text' => '',
        'sort_order' => 50,
        'is_enabled' => 1,
        'audience' => 'all',
        'item_type' => 'link',
        'admin_hint' => 'Terms of service page for wallet platform',
        'admin_route_hint' => BASE_URL . '/wallet_terms.php',
        'active_pages' => ['wallet_terms'],
    ],
    'wallet_download' => [
        'nav_key' => 'wallet_download',
        'location' => 'header',
        'section_key' => 'primary',
        'label' => 'Download APK',
        'route_key' => 'download',
        'icon_class' => 'fas fa-download',
        'badge_text' => '',
        'sort_order' => 60,
        'is_enabled' => 1,
        'audience' => 'all',
        'item_type' => 'link',
        'admin_hint' => 'APK download link for RexLink wallet',
        'admin_route_hint' => BASE_URL . '/api/rexlink_download.php',
        'active_pages' => ['wallet'],
    ],
    'wallet_how-it-works' => [
        'nav_key' => 'wallet_how-it-works',
        'location' => 'header',
        'section_key' => 'primary',
        'label' => 'How it Works',
        'route_key' => 'how-it-works',
        'icon_class' => 'fas fa-route',
        'badge_text' => '',
        'sort_order' => 70,
        'is_enabled' => 1,
        'audience' => 'all',
        'item_type' => 'link',
        'admin_hint' => 'How RexLink works page section',
        'admin_route_hint' => BASE_URL . '/wallet.php#how-it-works',
        'active_pages' => ['wallet'],
    ],
    'wallet_faq' => [
        'nav_key' => 'wallet_faq',
        'location' => 'header',
        'section_key' => 'primary',
        'label' => 'FAQ',
        'route_key' => 'faq',
        'icon_class' => 'fas fa-circle-question',
        'badge_text' => '',
        'sort_order' => 80,
        'is_enabled' => 1,
        'audience' => 'all',
        'item_type' => 'link',
        'admin_hint' => 'FAQ page section for wallet',
        'admin_route_hint' => BASE_URL . '/wallet.php#faq',
        'active_pages' => ['wallet'],
    ],
];