<?php
/**
 * Seed all 10 days of mission tasks into the mini_tasks table.
 * Run: C:\xampp\php\php.exe c:\xampp\htdocs\coinrex\tools\seed_mission_tasks.php
 */
require_once __DIR__ . '/../includes/config.php';

$db = getDBConnection();

// Define all 10 days of mission tasks
$mission_tasks = [
    // ===== DAY 1: Getting Started =====
    [
        'task_key' => 'day1_checkin',
        'title' => 'Daily Check-In',
        'description' => 'Check in to start your Day 1 mission.',
        'mission_day' => 1,
        'mission_step' => 0,
        'verification_mode' => 'instant',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 1.00,
        'completion_steps' => "1. Click the \"Check In Now\" button.\n2. Confirm your daily check-in.\n3. Earn your reward instantly!",
        'cta_label' => 'Check In Now',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day1_terms_quiz',
        'title' => 'Terms of Service Quiz',
        'description' => 'Read the Terms of Service and pass a short quiz.',
        'mission_day' => 1,
        'mission_step' => 1,
        'verification_mode' => 'quiz',
        'requires_quiz' => 1,
        'requires_manual_review' => 0,
        'min_quiz_score' => 1,
        'task_category' => 'custom',
        'reward' => 1.50,
        'completion_steps' => "1. Read the Terms of Service.\n2. Answer the quiz questions.\n3. Score 100% to earn the reward.",
        'cta_label' => 'Start Quiz',
        'learning_title' => 'Terms of Service',
        'learning_url' => BASE_URL . '/terms.php',
    ],
    [
        'task_key' => 'day1_profile_setup',
        'title' => 'Profile Setup',
        'description' => 'Complete your profile with avatar, full name, username, and country.',
        'mission_day' => 1,
        'mission_step' => 2,
        'verification_mode' => 'profile',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 1.50,
        'completion_steps' => "1. Go to your Profile page.\n2. Upload an avatar.\n3. Set your full name, username, and country.\n4. Return here and click Complete.",
        'cta_label' => 'Open Profile',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day1_social_follow',
        'title' => 'Follow CoinRex Socials',
        'description' => 'Follow CoinRex on X (Twitter) or Telegram and share your handle.',
        'mission_day' => 1,
        'mission_step' => 3,
        'verification_mode' => 'manual',
        'requires_quiz' => 0,
        'requires_manual_review' => 1,
        'task_category' => 'community_engagement',
        'reward' => 2.00,
        'completion_steps' => "1. Follow CoinRex on X (Twitter) or join the Telegram channel.\n2. Copy your X username or Telegram handle.\n3. Paste it below and submit for review.",
        'cta_label' => 'Submit for Review',
        'learning_title' => '',
        'learning_url' => '',
    ],

    // ===== DAY 2: Exploration =====
    [
        'task_key' => 'day2_checkin',
        'title' => 'Daily Check-In',
        'description' => 'Check in to start your Day 2 mission.',
        'mission_day' => 2,
        'mission_step' => 0,
        'verification_mode' => 'instant',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 2.00,
        'completion_steps' => "1. Click the \"Check In Now\" button.\n2. Confirm your daily check-in.\n3. Earn your reward instantly!",
        'cta_label' => 'Check In Now',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day2_explore_projects',
        'title' => 'Explore Projects',
        'description' => 'Browse the projects page and discover what CoinRex offers.',
        'mission_day' => 2,
        'mission_step' => 1,
        'verification_mode' => 'instant',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'website_visit',
        'reward' => 1.50,
        'completion_steps' => "1. Open the Projects page.\n2. Browse through the listed projects.\n3. Return here and click Complete.",
        'cta_label' => 'Open Projects',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day2_wallet_setup',
        'title' => 'Wallet Setup',
        'description' => 'Add your wallet address to your profile.',
        'mission_day' => 2,
        'mission_step' => 2,
        'verification_mode' => 'wallet',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 2.00,
        'completion_steps' => "1. Go to your Profile page.\n2. Add your wallet address.\n3. Return here and click Complete.",
        'cta_label' => 'Add Wallet',
        'learning_title' => '',
        'learning_url' => '',
    ],

    // ===== DAY 3: Community Engagement =====
    [
        'task_key' => 'day3_checkin',
        'title' => 'Daily Check-In',
        'description' => 'Check in to start your Day 3 mission.',
        'mission_day' => 3,
        'mission_step' => 0,
        'verification_mode' => 'instant',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 3.00,
        'completion_steps' => "1. Click the \"Check In Now\" button.\n2. Confirm your daily check-in.\n3. Earn your reward instantly!",
        'cta_label' => 'Check In Now',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day3_share_experience',
        'title' => 'Share Your Experience',
        'description' => 'Share your CoinRex experience on social media.',
        'mission_day' => 3,
        'mission_step' => 1,
        'verification_mode' => 'manual',
        'requires_quiz' => 0,
        'requires_manual_review' => 1,
        'task_category' => 'community_engagement',
        'reward' => 3.00,
        'completion_steps' => "1. Post about your CoinRex experience on X, Facebook, Binance Square, Medium, or Reddit.\n2. Copy the public post URL.\n3. Select your platform and paste the URL below.\n4. Submit for review.",
        'cta_label' => 'Submit for Review',
        'learning_title' => '',
        'learning_url' => '',
    ],

    // ===== DAY 4: Deep Dive =====
    [
        'task_key' => 'day4_checkin',
        'title' => 'Daily Check-In',
        'description' => 'Check in to start your Day 4 mission.',
        'mission_day' => 4,
        'mission_step' => 0,
        'verification_mode' => 'instant',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 4.00,
        'completion_steps' => "1. Click the \"Check In Now\" button.\n2. Confirm your daily check-in.\n3. Earn your reward instantly!",
        'cta_label' => 'Check In Now',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day4_boosthub_gateway',
        'title' => 'BoostHub Task',
        'description' => 'Complete a BoostHub task worth 2 $REX to continue.',
        'mission_day' => 4,
        'mission_step' => 1,
        'verification_mode' => 'boosthub',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 2.00,
        'completion_steps' => "1. Open BoostHub.\n2. Complete one task worth exactly 2 $REX.\n3. Return to TaskHub.",
        'cta_label' => 'Open BoostHub',
        'learning_title' => '',
        'learning_url' => '',
    ],

    // ===== DAY 5: Growth =====
    [
        'task_key' => 'day5_checkin',
        'title' => 'Daily Check-In',
        'description' => 'Check in to start your Day 5 mission.',
        'mission_day' => 5,
        'mission_step' => 0,
        'verification_mode' => 'instant',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 5.00,
        'completion_steps' => "1. Click the \"Check In Now\" button.\n2. Confirm your daily check-in.\n3. Earn your reward instantly!",
        'cta_label' => 'Check In Now',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day5_boosthub_gateway',
        'title' => 'BoostHub Task',
        'description' => 'Complete a BoostHub task worth 2 $REX to continue.',
        'mission_day' => 5,
        'mission_step' => 1,
        'verification_mode' => 'boosthub',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 2.00,
        'completion_steps' => "1. Open BoostHub.\n2. Complete one task worth exactly 2 $REX.\n3. Return to TaskHub.",
        'cta_label' => 'Open BoostHub',
        'learning_title' => '',
        'learning_url' => '',
    ],

    // ===== DAY 6: Consistency =====
    [
        'task_key' => 'day6_checkin',
        'title' => 'Daily Check-In',
        'description' => 'Check in to start your Day 6 mission.',
        'mission_day' => 6,
        'mission_step' => 0,
        'verification_mode' => 'instant',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 6.00,
        'completion_steps' => "1. Click the \"Check In Now\" button.\n2. Confirm your daily check-in.\n3. Earn your reward instantly!",
        'cta_label' => 'Check In Now',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day6_boosthub_gateway',
        'title' => 'BoostHub Task',
        'description' => 'Complete a BoostHub task worth 2 $REX to continue.',
        'mission_day' => 6,
        'mission_step' => 1,
        'verification_mode' => 'boosthub',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 2.00,
        'completion_steps' => "1. Open BoostHub.\n2. Complete one task worth exactly 2 $REX.\n3. Return to TaskHub.",
        'cta_label' => 'Open BoostHub',
        'learning_title' => '',
        'learning_url' => '',
    ],

    // ===== DAY 7: Advanced =====
    [
        'task_key' => 'day7_checkin',
        'title' => 'Daily Check-In',
        'description' => 'Check in to start your Day 7 mission.',
        'mission_day' => 7,
        'mission_step' => 0,
        'verification_mode' => 'instant',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 7.00,
        'completion_steps' => "1. Click the \"Check In Now\" button.\n2. Confirm your daily check-in.\n3. Earn your reward instantly!",
        'cta_label' => 'Check In Now',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day7_boosthub_gateway',
        'title' => 'BoostHub Task',
        'description' => 'Complete a BoostHub task worth 2 $REX to continue.',
        'mission_day' => 7,
        'mission_step' => 1,
        'verification_mode' => 'boosthub',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 2.00,
        'completion_steps' => "1. Open BoostHub.\n2. Complete one task worth exactly 2 $REX.\n3. Return to TaskHub.",
        'cta_label' => 'Open BoostHub',
        'learning_title' => '',
        'learning_url' => '',
    ],

    // ===== DAY 8: Mastery =====
    [
        'task_key' => 'day8_checkin',
        'title' => 'Daily Check-In',
        'description' => 'Check in to start your Day 8 mission.',
        'mission_day' => 8,
        'mission_step' => 0,
        'verification_mode' => 'instant',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 8.00,
        'completion_steps' => "1. Click the \"Check In Now\" button.\n2. Confirm your daily check-in.\n3. Earn your reward instantly!",
        'cta_label' => 'Check In Now',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day8_boosthub_gateway',
        'title' => 'BoostHub Task',
        'description' => 'Complete a BoostHub task worth 3 $REX to continue.',
        'mission_day' => 8,
        'mission_step' => 1,
        'verification_mode' => 'boosthub',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 3.00,
        'completion_steps' => "1. Open BoostHub.\n2. Complete one task worth exactly 3 $REX.\n3. Return to TaskHub.",
        'cta_label' => 'Open BoostHub',
        'learning_title' => '',
        'learning_url' => '',
    ],

    // ===== DAY 9: Excellence =====
    [
        'task_key' => 'day9_checkin',
        'title' => 'Daily Check-In',
        'description' => 'Check in to start your Day 9 mission.',
        'mission_day' => 9,
        'mission_step' => 0,
        'verification_mode' => 'instant',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 9.00,
        'completion_steps' => "1. Click the \"Check In Now\" button.\n2. Confirm your daily check-in.\n3. Earn your reward instantly!",
        'cta_label' => 'Check In Now',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day9_boosthub_gateway',
        'title' => 'BoostHub Task',
        'description' => 'Complete a BoostHub task worth 3 $REX to continue.',
        'mission_day' => 9,
        'mission_step' => 1,
        'verification_mode' => 'boosthub',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 3.00,
        'completion_steps' => "1. Open BoostHub.\n2. Complete one task worth exactly 3 $REX.\n3. Return to TaskHub.",
        'cta_label' => 'Open BoostHub',
        'learning_title' => '',
        'learning_url' => '',
    ],

    // ===== DAY 10: Graduation =====
    [
        'task_key' => 'day10_checkin',
        'title' => 'Daily Check-In',
        'description' => 'Check in to start your final Day 10 mission.',
        'mission_day' => 10,
        'mission_step' => 0,
        'verification_mode' => 'instant',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 10.00,
        'completion_steps' => "1. Click the \"Check In Now\" button.\n2. Confirm your daily check-in.\n3. Earn your reward instantly!",
        'cta_label' => 'Check In Now',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day10_boosthub_gateway',
        'title' => 'BoostHub Task',
        'description' => 'Complete a BoostHub task worth 3 $REX to continue.',
        'mission_day' => 10,
        'mission_step' => 1,
        'verification_mode' => 'boosthub',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 3.00,
        'completion_steps' => "1. Open BoostHub.\n2. Complete one task worth exactly 3 $REX.\n3. Return to TaskHub.",
        'cta_label' => 'Open BoostHub',
        'learning_title' => '',
        'learning_url' => '',
    ],
    [
        'task_key' => 'day10_mystery_box',
        'title' => 'Mystery Box',
        'description' => 'Open your mystery box reward for completing the mission!',
        'mission_day' => 10,
        'mission_step' => 2,
        'verification_mode' => 'mystery',
        'requires_quiz' => 0,
        'requires_manual_review' => 0,
        'task_category' => 'custom',
        'reward' => 20.00,
        'completion_steps' => "1. Click the \"Open Mystery Box\" button.\n2. Claim your reward!\n3. Congratulations on completing the mission!",
        'cta_label' => 'Open Mystery Box',
        'learning_title' => '',
        'learning_url' => '',
    ],
];

// First, delete existing mission tasks to avoid duplicates
$db->exec("DELETE FROM mini_tasks WHERE task_group = 'mission'");
echo "Deleted existing mission tasks.\n";

// Insert all mission tasks
$stmt = $db->prepare("
    INSERT INTO mini_tasks (
        task_key, title, description, mission_day, mission_step, 
        verification_mode, requires_quiz, requires_manual_review, min_quiz_score,
        task_category, reward, completion_steps, cta_label,
        learning_title, learning_url, task_group, is_active,
        daily_limit, cooldown_seconds
    ) VALUES (
        ?, ?, ?, ?, ?,
        ?, ?, ?, ?,
        ?, ?, ?, ?,
        ?, ?, 'mission', 1,
        1, 86400
    )
");

$count = 0;
foreach ($mission_tasks as $task) {
    $stmt->execute([
        $task['task_key'],
        $task['title'],
        $task['description'],
        $task['mission_day'],
        $task['mission_step'],
        $task['verification_mode'],
        $task['requires_quiz'],
        $task['requires_manual_review'],
        $task['min_quiz_score'] ?? 0,
        $task['task_category'],
        $task['reward'],
        $task['completion_steps'],
        $task['cta_label'],
        $task['learning_title'],
        $task['learning_url'],
    ]);
    $count++;
}

echo "Inserted $count mission tasks successfully.\n";

// Verify
$verify = $db->query("SELECT COUNT(*) FROM mini_tasks WHERE task_group = 'mission' AND is_active = 1");
echo "Total active mission tasks in DB: " . $verify->fetchColumn() . "\n";

// Show by day
$by_day = $db->query("SELECT mission_day, COUNT(*) as cnt FROM mini_tasks WHERE task_group = 'mission' AND is_active = 1 GROUP BY mission_day ORDER BY mission_day");
echo "\nTasks by day:\n";
foreach ($by_day as $row) {
    echo "  Day {$row['mission_day']}: {$row['cnt']} tasks\n";
}
