<link rel="stylesheet" href="<?php echo ASSETS_URL; ?>/css/submit-review.css?v=<?php echo (int) @filemtime(dirname(__DIR__, 2) . '/assets/css/submit-review.css'); ?>">
<main class="review-flow-main">
<div class="review-flow-shell">
<div id="reviewToastContainer" class="review-toast-container" aria-live="polite"></div>
<header class="review-flow-hero">
    <div><span class="review-eyebrow"><i class="fas fa-shield-check"></i> Verified community review</span><h1>Share your experience with <?php echo $project ? esc($project['name']) : 'a project'; ?></h1><p>Submit manual wallet proof, write a useful review, and confirm everything before submitting.</p></div>
    <?php if ($project): ?><div class="review-hero-reward"><span>Potential reward</span><strong>Up to <?php echo esc(number_format($project_max_reward, 0)); ?> REX</strong><small>Final reward depends on review quality and approval.</small></div><?php endif; ?>
</header>
<?php if (!$project): ?>
<section class="review-empty-state"><i class="fas fa-folder-open"></i><h2><?php echo $project_id > 0 ? 'Project not found' : 'Choose a project first'; ?></h2><p>Open an approved project and select Write Review to begin.</p><a class="review-button is-primary" href="<?php echo BASE_URL; ?>/public/projects.php">Browse Projects</a></section>
<?php elseif ($submission_success): ?>
<section class="review-success-state">
    <span class="review-success-icon"><i class="fas fa-check"></i></span>
    <span class="review-eyebrow">Submission complete</span>
    <h1><?php echo ($submission_success['status'] ?? '') === 'approved' ? 'Your review is approved' : 'Your review is now pending'; ?></h1>
    <p><?php echo ($submission_success['status'] ?? '') === 'approved' ? 'Your verified review has been published and the confirmed reward was applied.' : 'Moderation will verify the proof and review quality. This usually takes 24–48 hours.'; ?></p>
    <div class="review-success-metrics"><div><span>Status</span><strong><?php echo esc(ucfirst((string) ($submission_success['status'] ?? 'pending'))); ?></strong></div><div><span>Proof</span><strong><?php echo esc(ucfirst((string) ($submission_success['proof_status'] ?? 'pending'))); ?></strong></div><div><span><?php echo !empty($submission_success['reward_confirmed']) ? 'Reward' : 'Estimated reward'; ?></span><strong><?php echo esc(number_format((float) ($submission_success['reward_rex'] ?? 0), 2)); ?> REX</strong></div></div>
    <div class="review-success-actions"><a class="review-button is-primary" href="<?php echo BASE_URL; ?>/public/my-reviews.php">View My Reviews</a><a class="review-button is-secondary" href="<?php echo BASE_URL; ?>/public/project-detail.php?id=<?php echo (int) $project['id']; ?>">Back to Project</a></div>
<script>try{localStorage.removeItem(<?php echo json_encode('coinrex_review_draft_v3_' . (int) $project['id']); ?>);}catch(e){}</script>
</section>
<?php elseif ($existing_project_review): ?>
<section class="review-empty-state"><i class="fas fa-lock"></i><span class="review-eyebrow">Review already submitted</span><h2>You already reviewed <?php echo esc($project['name']); ?></h2><p>CoinRex permits one review per user for each project.</p><div class="review-success-metrics"><div><span>Status</span><strong><?php echo esc(ucfirst((string) ($existing_project_review['status'] ?? 'pending'))); ?></strong></div><div><span>Proof</span><strong><?php echo esc(ucfirst((string) ($existing_project_review['proof_status'] ?? 'pending'))); ?></strong></div></div><div class="review-success-actions"><a class="review-button is-primary" href="<?php echo BASE_URL; ?>/public/my-reviews.php">View My Reviews</a><a class="review-button is-secondary" href="<?php echo BASE_URL; ?>/public/project-detail.php?id=<?php echo (int) $project['id']; ?>">Back to Project</a></div>
<script>try{localStorage.removeItem(<?php echo json_encode('coinrex_review_draft_v3_' . (int) $project['id']); ?>);}catch(e){}</script></section>
<?php else: ?>
<section class="review-project-strip">
    <div class="review-project-identity"><div class="review-project-logo<?php echo $project_logo_url ? ' has-image' : ''; ?>"<?php if ($project_logo_url): ?> style="background-image:url('<?php echo esc($project_logo_url); ?>')"<?php endif; ?>><?php echo $project_logo_url ? '' : esc(strtoupper(substr($project['name'], 0, 2))); ?></div><div><span>Reviewing</span><strong><?php echo esc($project['name']); ?><?php if (!empty($project['is_verified'])): ?> <i class="fas fa-circle-check"></i><?php endif; ?></strong></div></div>
    <div class="review-project-facts"><div><span>Minimum hold</span><strong><?php echo esc($format_clean_amount($project_min_hold)); ?> <?php echo esc($project_token_symbol); ?></strong></div><div><span>Holding period</span><strong><?php echo (int) $project_hold_days; ?> day<?php echo $project_hold_days === 1 ? '' : 's'; ?></strong></div><div><span>Review limit</span><strong>One per project</strong></div></div>
</section>
<?php if ($error): ?><div class="review-server-error" role="alert"><i class="fas fa-circle-exclamation"></i><div><strong>We could not submit the review</strong><p><?php echo $error; ?></p></div></div><?php endif; ?>
<form method="POST" enctype="multipart/form-data" id="reviewForm" novalidate>
<input type="hidden" name="project_id" value="<?php echo (int) $project['id']; ?>"><input type="hidden" name="csrf_token" value="<?php echo esc($page_csrf_token); ?>"><input type="hidden" name="proof_method" id="proof_method" value="manual"><input type="hidden" name="wallet_address" id="wallet_address" value="<?php echo esc($form['wallet_address']); ?>"><input type="hidden" name="wallet_type" value="non_custodial"><input type="hidden" name="holding_amount" value="<?php echo esc($form['holding_amount'] !== '' ? $form['holding_amount'] : $project_min_hold); ?>"><input type="hidden" name="holding_days" value="<?php echo esc($form['holding_days'] !== '' ? $form['holding_days'] : $project_hold_days); ?>"><input type="hidden" name="verification_confirmed" id="verification_confirmed" value="0"><input class="review-honeypot" type="text" name="website" tabindex="-1" autocomplete="off">
<nav class="review-stepper" aria-label="Review submission progress">
<button type="button" data-review-nav="1" class="is-active" aria-current="step"><span>1</span><div><strong>Verify</strong><small>Eligibility</small></div></button><button type="button" data-review-nav="2"><span>2</span><div><strong>Write</strong><small>Your review</small></div></button><button type="button" data-review-nav="3"><span>3</span><div><strong>Confirm</strong><small>Preview & submit</small></div></button>
</nav>
<div class="review-flow-card">
<section data-review-step="1" class="review-step">
<div class="review-step-heading"><div><span class="review-eyebrow">Step 1 of 3</span><h2>Submit manual eligibility proof</h2><p>Manual submission is live now. Instant verification and live monitoring are coming soon.</p></div><span class="review-wallet-chip"><i class="fas fa-wallet"></i><span data-current-wallet><?php echo esc($form['wallet_address'] ?: 'Not connected'); ?></span></span></div>
<div id="reviewVerificationState" class="review-state-card is-manual"><span class="review-state-icon"><i id="reviewVerificationIcon" class="fas fa-file-shield"></i></span><div><h3 id="reviewVerificationTitle">Manual proof selected</h3><p id="reviewVerificationMessage">Provide wallet address, transaction hash, and screenshot. Review usually takes 24-48 hours.</p></div><button type="button" id="reviewVerificationRetry" class="review-text-button" hidden>Retry</button></div>
<div id="reviewVerificationReport" class="review-verification-report" hidden></div>
<div id="reviewConnectionChoices" class="review-connection-area">
    <button type="button" id="reviewUseManual" class="review-wallet-option is-primary"><span class="review-option-icon"><i class="fas fa-file-arrow-up"></i></span><div><strong>Manual proof</strong><small>Live now: submit TX hash and screenshot</small></div><i class="fas fa-arrow-right"></i></button>
    <div id="reviewOtherMethods" class="review-other-methods"><span>Verification methods</span><div><button type="button" id="reviewUseRexLink" class="is-disabled" disabled aria-disabled="true"><i class="fas fa-link"></i><strong>Instant verification</strong><small>RexLink wallet session</small><span class="review-soon-badge">Soon</span></button><button type="button" id="reviewUseExternal" class="is-disabled" disabled aria-disabled="true"><i class="fas fa-wallet"></i><strong>Browser wallet</strong><small>Instant signature check</small><span class="review-soon-badge">Soon</span></button><button type="button" id="reviewStartLive" class="is-disabled" disabled aria-disabled="true"><i class="fas fa-clock"></i><strong>Live monitoring</strong><small>Automated balance watch</small><span class="review-soon-badge">Soon</span></button></div></div>
    <div id="reviewEligibilityFallbacks" class="review-fallbacks" hidden><p>Already received the project token after wallet verification?</p><button type="button" class="review-text-button" onclick="document.getElementById('reviewUseManual').click()">Use Manual Proof</button></div>
</div><div id="reviewQrPanel" class="review-inline-panel review-qr-panel" hidden>
    <div class="review-inline-head"><div><span class="review-eyebrow">RexLink pairing</span><h3>Create a session only when ready</h3><p>An existing valid session is always reused first. QR generation is never automatic.</p></div><button type="button" id="reviewCreateSession" class="review-button is-primary">Create RexLink Session</button></div>
    <div class="review-qr-layout"><div><div id="reviewQrStage" class="review-qr-stage"><span>QR will appear here after you request it.</span></div><img id="reviewQrImage" alt="RexLink pairing QR" hidden><span id="reviewQrLogo" hidden></span></div><div class="review-pairing-instructions"><ol><li>Open RexLink on your phone.</li><li>Scan the QR or enter the code.</li><li>Approve the CoinRex session.</li></ol><div class="review-code-box"><span id="reviewPairingCode">------</span><button type="button" id="reviewCopyPairingCode" disabled aria-label="Copy pairing code"><i class="fas fa-copy"></i></button></div><small id="reviewPairingTimer">No QR created</small></div></div>
</div>
<div id="reviewMonitoringPanel" class="review-inline-panel review-monitor-panel" hidden><span class="review-monitor-icon"><i class="fas fa-signal"></i></span><div><span class="review-eyebrow">Live verification</span><h3 id="reviewMonitoringTimer">00:00</h3><p id="reviewMonitoringDetail">CoinRex is monitoring the required token balance.</p></div></div>
<div id="reviewManualPanel" class="review-inline-panel">
    <div class="review-inline-head"><div><span class="review-eyebrow">Manual submission</span><h3>Submit wallet proof</h3><p>Never upload a seed phrase, private key, or recovery phrase.</p></div><button type="button" id="reviewBackToWallet" class="review-text-button" hidden>Choose another method</button></div>
    <div class="review-field-grid"><label class="review-field"><span>Wallet address <b>*</b></span><input type="text" name="manual_wallet_address" id="manual_wallet_address" value="<?php echo $form['proof_method'] === 'manual' ? esc($form['wallet_address']) : ''; ?>" placeholder="0x…" autocomplete="off"></label><label class="review-field"><span>Transaction hash <b>*</b></span><input type="text" name="tx_hash" id="tx_hash" value="<?php echo esc($form['tx_hash']); ?>" placeholder="Paste the qualifying transaction hash"></label></div>
    <label class="review-upload review-field" for="screenshotInput"><input type="file" name="screenshot" id="screenshotInput" accept="image/png,image/jpeg,image/webp,image/gif"><i class="fas fa-cloud-arrow-up"></i><strong>Upload screenshot proof</strong><span id="reviewScreenshotName">PNG, JPG, WEBP or GIF — maximum 5 MB</span></label>
</div>
</section>
<section data-review-step="2" class="review-step" hidden>
<div class="review-step-heading"><div><span class="review-eyebrow">Step 2 of 3</span><h2>Write an experience people can use</h2><p>Be specific about what you tried, what worked, and what other users should know.</p></div></div>
<div class="review-field"><label for="review_title">Review title <b>*</b></label><input type="text" name="review_title" id="review_title" value="<?php echo esc($form['review_title']); ?>" placeholder="Clear summary of your experience" maxlength="160"></div>
<div class="review-field" id="overallRatingGroup"><span class="review-field-label">Overall rating <b>*</b></span><div class="review-overall-rating" role="group" aria-label="Overall rating"><?php for ($i=1;$i<=5;$i++): ?><button type="button" data-overall-rating="<?php echo $i; ?>" aria-pressed="false" aria-label="<?php echo $i; ?> stars"><i class="fas fa-star"></i></button><?php endfor; ?><strong id="overallRatingLabel">Choose rating</strong></div><input type="hidden" name="rating" id="rating" value="<?php echo esc($form['rating']); ?>"></div>
<div class="review-prompt-row"><button type="button" data-review-prompt="I used this project for ">Used for</button><button type="button" data-review-prompt="What worked well was ">Worked well</button><button type="button" data-review-prompt="The confusing part was ">Confusing</button><button type="button" data-review-prompt="Other users should know ">Worth knowing</button></div>
<div class="review-field"><div class="review-label-row"><label for="review_content">Your review <b>*</b></label><span id="reviewCharacterCount">0 / 150 minimum</span></div><textarea name="review_content" id="review_content" rows="8" placeholder="Describe your real experience with enough detail to help another user."><?php echo esc($form['review_content']); ?></textarea><div id="reviewQualityMeter" class="review-quality-meter" data-label="Keep writing"><span></span></div></div>
<div class="review-score-section"><div><span class="review-eyebrow">Detailed scorecard</span><h3>Rate each part of the experience</h3><p>Use 1 for poor and 5 for excellent.</p></div><div class="review-score-grid">
<?php foreach ($experience_score_fields as $field_name=>$score): ?><article class="review-score-card" data-score-group="<?php echo esc($field_name); ?>"><div><strong><?php echo esc($score['label']); ?></strong><small><?php echo esc($score['hint']); ?></small></div><div class="review-segmented" role="group" aria-label="<?php echo esc($score['label']); ?> rating"><?php for($value=1;$value<=5;$value++): ?><button type="button" data-value="<?php echo $value; ?>" aria-pressed="false"><?php echo $value; ?></button><?php endfor; ?></div><input type="hidden" name="<?php echo esc($field_name); ?>" value="<?php echo esc($form[$field_name]); ?>" data-score-input data-label="<?php echo esc($score['label']); ?>"></article><?php endforeach; ?>
</div></div>
<div class="review-field-grid"><label class="review-field"><span>Pros <small>Optional</small></span><textarea name="pros" id="pros" rows="4" placeholder="What stood out positively?"><?php echo esc($form['pros']); ?></textarea></label><label class="review-field"><span>Cons <small>Optional</small></span><textarea name="cons" id="cons" rows="4" placeholder="What could be improved?"><?php echo esc($form['cons']); ?></textarea></label></div>
</section><section data-review-step="3" class="review-step" hidden>
<div class="review-step-heading"><div><span class="review-eyebrow">Step 3 of 3</span><h2>Review before submitting</h2><p>Confirm the wallet proof, ratings, and review content.</p></div></div>
<div class="review-summary-grid">
<article class="review-summary-card"><div class="review-summary-head"><div><i class="fas fa-shield-check"></i><strong>Verification</strong></div><button type="button" data-edit-step="1">Edit</button></div><dl><div><dt>Project</dt><dd id="summaryProject"></dd></div><div><dt>Wallet</dt><dd id="summaryWallet"></dd></div><div><dt>Method</dt><dd id="summaryMethod"></dd></div></dl></article>
<article class="review-summary-card"><div class="review-summary-head"><div><i class="fas fa-star"></i><strong>Review</strong></div><button type="button" data-edit-step="2">Edit</button></div><h3 id="summaryTitle">No title yet</h3><div class="review-summary-rating"><span id="summaryRating">–</span><small>Overall</small></div><p id="summaryContent">Your review preview will appear here.</p></article>
</div>
<article class="review-summary-card is-wide"><div class="review-summary-head"><div><i class="fas fa-chart-simple"></i><strong>Experience scorecard</strong></div><button type="button" data-edit-step="2">Edit</button></div><div id="summaryCategories" class="review-summary-categories"></div></article>
<div class="review-submit-total"><div><span>Estimated review reward</span><strong data-reward-estimate>0.00 REX</strong><small>This estimate is provisional until approval.</small></div><i class="fas fa-coins"></i></div>
<label class="review-consent"><input type="checkbox" name="terms_accepted" value="1" id="termsCheckbox" <?php echo $form['terms_accepted']==='1'?'checked':''; ?>><span class="review-consent-box"><i class="fas fa-check"></i></span><span>I confirm this is my honest experience and agree to the <a href="<?php echo BASE_URL; ?>/public/terms.php" target="_blank" rel="noopener">Review Submission Terms</a>.</span></label>
</section>
<div class="review-action-bar"><button type="button" id="reviewBackButton" class="review-button is-secondary" hidden><i class="fas fa-arrow-left"></i> Back</button><span class="review-action-note"><i class="fas fa-lock"></i> Draft saved locally. Manual proof is reviewed by CoinRex.</span><button type="button" id="reviewNextButton" class="review-button is-primary" disabled>Continue to Review</button><button type="submit" name="submit_review" id="reviewSubmitButton" class="review-button is-primary" hidden><i class="fas fa-paper-plane"></i> Submit Review</button></div>
</div>
</form>
<?php endif; ?>
</div>
</main>
<?php if ($project && !$existing_project_review && !$submission_success): ?>
<script src="<?php echo ASSETS_URL; ?>/js/qrcode-browser.js?v=<?php echo (int) @filemtime(dirname(__DIR__, 2) . '/assets/js/qrcode-browser.js'); ?>"></script>
<script src="<?php echo ASSETS_URL; ?>/js/rexlink-pairing.js?v=<?php echo (int) @filemtime(dirname(__DIR__, 2) . '/assets/js/rexlink-pairing.js'); ?>"></script>
<script>
window.CoinRexReviewConfig=<?php echo json_encode([
'projectId'=>(int)$project['id'],'projectName'=>(string)$project['name'],'accountWallet'=>strtolower((string)($user['wallet_address']??'')),'maxReward'=>(float)$project_max_reward,'networkSlugs'=>$rexlink_review_network_slugs,'publicBaseUrl'=>(defined('PUBLIC_BASE_URL')?PUBLIC_BASE_URL:BASE_URL),
'preflightUrl'=>BASE_URI.'/api/review-eligibility/preflight.php','instantUrl'=>BASE_URI.'/api/review-eligibility/instant.php','liveCheckUrl'=>BASE_URI.'/api/review-eligibility/check.php','statusUrl'=>BASE_URI.'/api/review-eligibility/status.php','nonceUrl'=>BASE_URI.'/api/review-eligibility/wallet_nonce.php','verifyWalletUrl'=>BASE_URI.'/api/review-eligibility/verify_wallet.php','rexLinkWalletUrl'=>BASE_URI.'/api/review-eligibility/rexlink_wallet.php','createPairingUrl'=>BASE_URI.'/api/review-eligibility/create_rexlink_pairing.php','pairingQrUrl'=>BASE_URI.'/api/rex-signer/pairing_qr.php'
],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE); ?>;
</script>
<script src="<?php echo ASSETS_URL; ?>/js/submit-review.js?v=<?php echo (int) @filemtime(dirname(__DIR__, 2) . '/assets/js/submit-review.js'); ?>"></script>
<?php endif; ?>